name: HoloItems
version: '1.3'
author: klin
main: com.klin.holoItems.HoloItems
api-version: '1.20'
depend: []

commands:
  collections:
    permission: holoItems.player
    usage: /<command>
  coordinates:
    permission: holoItems.player
    usage: /<command>
  custommodeldata:
    permission: holoItems.player
    usage: /<command>
  acquire:
    permission: holoItems.player
    usage: /<command> <id>
  giveholo:
    permission: holoItems.op
    usage: /<command> <player> <id>
  accelerate:
    permission: holoItems.op
    usage: /<command> <x> <y> <z>
  canceltasks:
    permission: holoItems.op
    usage: /<command>
  clearactivatables:
    permission: holoItems.op
    usage: /<command>
  collect:
    permission: holoItems.op
    usage: /<command> <stat> <type> <id>
  revert:
    permission: holoItems.op
    usage: /<command>
  convert:
    permission: holoItems.op
    usage: /<command> <id>
  disable:
    permission: holoItems.op
    usage: /<command> <id>
  enable:
    permission: holoItems.op
    usage: /<command> <id>
  getactivatables:
    permission: holoItems.op
    usage: /<command>
  gethead:
    permission: holoItems.op
    usage: /<command> <name>
  getmap:
    permission: holoItems.op
    usage: /<command> <index>
  removechunktickets:
    permission: holoItems.op
    usage: /<command>
  setcustommodeldata:
    permission: holoItems.op
    usage: /<command> <custommodeldata>
  setenchantments:
    permission: holoItems.op
    usage: /<command> <enchantments>
  setid:
    permission: holoItems.op
    usage: /<command> <id>
  settype:
    permission: holoItems.op
    usage: /<command> <type>
  tasks:
    permission: holoItems.op
    usage: /<command>
  test:
    permission: holoItems.op
    usage: /<command>
  
  inadungeon:
    permission: holoItems.dungeon
    usage: /<command>
  build:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <name> <world> <x> <y> <z>
  tostring:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x1> <y1> <z1> <x2> <y2> <z2> <name>
  reset:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <name>
  shop:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  groundpound:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <entityType>
  paintbomb:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  spreadfire:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  freeze:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  select:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  conduit:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  cookie:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  deadbeats:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z> <amount>
  plant:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  minesweeper:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x1> <x2> <z1> <z2> <y>
  class:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <class>
  maintain:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <x1> <z1> <x2> <z2>
  payload:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z1> <z2>
  guide:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  waterfall:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>

permissions:
  holoItems.*:
    default: op
    children:
      holoItems.player: true
      holoItems.op: true
      holoItems.dungeons: true
  holoItems.player:
    default: true
  holoItems.op:
    default: false
  holoitems.dungeons:
    default: false
